import {COUNTRIES,LOCALES,SOURCE,normalize,normalizeApp,appId,escapeHTML as e,safeURL,relevance,actionFor,competition,analyzeDraft,charCount,byteCount,tokens,parseCSV,toCSV,importPopularity,importAnalytics,draftProposal,inferProfile,appendPopularity,popularityTrend} from './engine.js';
import {Workspace,scopeKey} from './storage.js';
import {AppleProvider} from './provider.js';
import * as V from './views.js';

const root=document.querySelector('#root'),modal=document.querySelector('#modal'),fileInput=document.querySelector('#file-input');
let seed,db,provider,view='keywords',selectedTerm='akari',locale='en-US',filter='',sort='relevance',trackedOnly=false,targetWord='',busy='',chartType='apps-free',trendRelevantOnly=true,toastTimer,saveTimer,fileMode='',fileScope,modalResults=[],pendingImport=null;
const chartCache=new Map(),reviewsCache=new Map();
function toast(text,error=false){const t=document.querySelector('#toast');t.textContent=text;t.className='show'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.className='',error?10000:4500);}
function report(error){const message=error?.message||'操作没有完成，请检查输入或稍后再试。';if(modal.open){modal.querySelector('.dialog-error')?.remove();const box=document.createElement('div');box.className='notice red dialog-error';box.setAttribute('role','alert');box.textContent=message;modal.querySelector('.modal-content')?.prepend(box);}else toast(message,true);}
function publicDraft(sc){return {title:sc.metadata.name,subtitle:sc.metadata.subtitle??'',keywords:sc.importedKeywords??''};}
function getDraft(sc=db.current,lang=locale){if(!sc.drafts[lang])sc.drafts[lang]={title:lang==='en-US'?sc.metadata.name:'',subtitle:lang==='en-US'?sc.metadata.subtitle??'':'',keywords:'',notes:'',description:lang==='en-US'?sc.metadata.description??'':'',promotionalText:''};return sc.drafts[lang];}
function context(){const sc=db.current,app=sc.metadata,country=db.selection.country;if(!sc.words[selectedTerm])selectedTerm=Object.keys(sc.words)[0]??'';return {seed,db,sc,app,country,view,locale,selectedTerm,filter,sort,trackedOnly,targetWord,busy,trendRelevantOnly,publicDraft:publicDraft(sc),draft:getDraft(sc),chartType,chart:chartCache.get(country+'|'+chartType)??seed.charts?.find(x=>x.country===country&&x.type===chartType),reviews:reviewsCache.get(scopeKey(app.id,country))??seed.reviews?.find(x=>x.appId===app.id&&x.country===country)};}
function render(){view=V.NAV[view]?view:'keywords';const c=context();const notice=c.app.countryUnverified?'<div class="notice amber section-gap">所选地区的应用资料尚未读取，当前仅使用已知的产品特征。请更新资料或切换到已验证地区。</div>':'';root.innerHTML=V.shell(c,notice+V[view](c));root.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>img.remove(),{once:true}));}
function navigate(v){if(location.hash.slice(1)===v){view=v;render();}else location.hash=v;modal.close();}
function showModal(title,body){modal.innerHTML=`<div class="modal-head"><h2>${e(title)}</h2>${V.button('×','close-modal','ghost','aria-label="关闭弹窗"')}</div><div class="modal-content">${body}</div>`;if(!modal.open)modal.showModal();modal.querySelector('input:not([type=hidden]),textarea,button.primary')?.focus();}
function download(name,content,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function safeName(s){return normalize(s).replace(/[^\p{L}\p{N}_-]+/gu,'-').slice(0,60)||'app';}
function pickFile(mode,accept='.csv,text/csv'){fileMode=mode;fileScope={...db.selection,locale};fileInput.accept=accept;fileInput.value='';fileInput.click();}
async function job(label,fn){if(busy){toast('当前任务还在进行，请等待完成。');return;}busy=label;render();try{await fn();}catch(error){report(error);}finally{busy='';render();}}
function saveDraft(){const d=getDraft();d.savedAt=new Date().toISOString();db.save();const node=document.querySelector('#draft-save-status');if(node)node.textContent=db.error??'已保存 '+V.time(d.savedAt);}
function candidateById(id){const sc=db.current;return sc.competitors.find(x=>x.id===id)??modalResults.find(x=>x.id===id)??Object.values(sc.words).flatMap(x=>x.record?.topResults??[]).find(x=>x.id===id);}
async function query(term,capture){
 const {id,country,app}=capture;try{const r=await provider.rank(term,country,app,true);db.record(r);return r;}catch(error){db.record({appId:id,country,term,source:SOURCE,status:'error',checkedAt:new Date().toISOString(),error:error.message,position:null,topResults:[]});throw error;}
}
async function queryTerms(terms){if(!terms.length){toast('请先添加关键词，或关注需要查询的词。');return;}const app={...db.current.metadata},capture={id:app.id,country:db.selection.country,app};await job('正在查询关键词…',async()=>{for(let i=0;i<terms.length;i++){busy=`${COUNTRIES[capture.country]} · ${i+1} / ${terms.length} · 查询 ${terms[i]}`;render();await query(terms[i],capture);}toast(`已完成 ${terms.length} 个词的查询，结果已保存在本机。`);});}
async function refreshMetadata(id=db.selection.appId,country=db.selection.country){const sc=db.ensure(id,country),before=sc.metadata;const x=await provider.lookup(id,country,true);sc.metadata={...x.app,subtitle:before.subtitle??'',subtitleSource:before.subtitleSource??'尚未读取',checkedAt:x.checkedAt,sourceURL:x.sourceURL,country,countryUnverified:false};sc.profile.kind==='custom'&&(sc.profile=inferProfile(sc.metadata));db.save();}
function manageApps(competitor=false){const appOptions=Object.values(db.state.apps);showModal(competitor?'添加竞品':'管理多个 App',`${!competitor?`<div class="result-list">${appOptions.map(a=>`<div class="result-item">${V.appIcon(a)}<div class="result-body"><h3>${e(a.name)}</h3><p>ID ${e(a.id)}</p></div>${V.button('切换','switch-app','',`data-id="${e(a.id)}"`)}</div>`).join('')}</div>`:''}<form id="app-search-form" class="modal-form section-gap"><input type="hidden" name="role" value="${competitor?'competitor':'app'}"><label>App ID、App Store 链接或名称<input name="query" required placeholder="6813927466，或应用名称" autocomplete="off"></label><p class="muted small">查询地区：${e(COUNTRIES[db.selection.country])}。添加名称时先搜索，再选择正确的 App。</p><button type="submit" class="primary">查询公开 App 资料</button></form>`);}
function addCompetitor(app){if(app.id===db.selection.appId)throw new Error('当前 App 不需要加入自己的竞品列表。');if(!db.current.competitors.some(x=>x.id===app.id)){db.current.competitors.push(app);db.save();}modal.close();render();toast('已加入当前地区的竞品比较。');}
function details(term){const w=db.current.words[term],r=w?.record;if(!r||r.status!=='ok'){toast('请先查询这个关键词。');return;}modalResults=r.topResults;showModal(term+' · 头部公开搜索结果',`<div class="notice">${e(r.country.toUpperCase())} · API 返回 ${r.returned} 条 · ${V.time(r.checkedAt)}。这里展示前 ${r.topResults.length} 个；不包含隐藏关键词。</div>${V.resultsList(r.topResults,{positions:true,action:'add-known-competitor',label:'加入比较'})}<p class="evidence-note"><a href="${e(safeURL(r.sourceURL??'https://itunes.apple.com/search?term='+encodeURIComponent(term)+'&country='+r.country+'&entity=software&limit=200'))}" target="_blank" rel="noopener noreferrer">查看原始公开来源 ↗</a></p>`);}
function csvWords(){const c=context();const rows=[['keyword','country','source','apiPosition','status','returned','checkedAt','popularity','popularityPeriod','competitionEstimate','relevance','tracked']];Object.values(c.sc.words).forEach(w=>{const p=db.state.popularity[c.country+'|'+w.term],comp=competition(w.record,c.app);rows.push([w.term,c.country,w.record?.source??'',w.record?.status==='ok'?(w.record.position??'not_found'):'',w.record?.status??'not_queried',w.record?.returned??'',w.record?.checkedAt??'',p?.score??'',p?.period??'',comp?.score??'',relevance(w.term,c.sc.profile).label,w.tracked?'yes':'no']);});return toCSV(rows);}
function exportDraft(all=false){const c=context();if(all){download(`${safeName(c.app.name)}-${c.country}-locales.json`,JSON.stringify({appId:c.app.id,country:c.country,source:'local-drafts',exportedAt:new Date().toISOString(),drafts:c.sc.drafts},null,2),'application/json');return;}const d=c.draft;download(`${safeName(c.app.name)}-${c.country}-${c.locale}.txt`,`App: ${c.app.name}\nApp ID: ${c.app.id}\nStorefront: ${c.country}\nLocale: ${c.locale}\nSource: local draft, not applied to App Store Connect\n\nTITLE\n${d.title}\n\nSUBTITLE\n${d.subtitle}\n\nKEYWORDS\n${d.keywords}\n\nPROMOTIONAL TEXT\n${d.promotionalText??''}\n\nDESCRIPTION\n${d.description??''}\n\nRATIONALE\n${d.notes??''}\n\nCHECKS\n${analyzeDraft(d,c.locale,c.app.category).issues.map(x=>x.message).join('\n')||'No length or duplicate issues detected.'}`);}
function importPreview(title,data,summary){pendingImport=data;showModal(title,`<div class="notice">${e(summary)}</div>${data.errors?.length?`<div class="notice amber">${data.errors.length} 行未通过检查：<br>${data.errors.slice(0,8).map(e).join('<br>')}</div>`:''}<pre>${e(JSON.stringify(data.values?.slice(0,5)??{},null,2))}</pre><div class="modal-footer">${V.button('取消','close-modal')}${data.values?.length?V.button('导入有效行','apply-import','primary'):''}</div>`);}
function showExperiments(){const a=db.current.experiments;showModal('实验日志',a.length?a.slice().reverse().map(x=>`<article class="experiment"><h3>${e(x.version||'未注明版本')} · ${e(x.locale)}</h3><p>计划发布日期：${e(x.releaseDate||'未提供')} · 创建于 ${V.time(x.createdAt)}</p><p>${e(x.hypothesis)}</p><p class="mono">${e(x.draft.title)} / ${e(x.draft.subtitle)}</p><div class="toolbar">${V.button('恢复为当前草稿','restore-experiment','',`data-id="${e(x.id)}"`)}</div></article>`).join(''):V.empty('尚未记录实验','在文案工作室填写假设后记录。'));}
async function action(name,node){
 const term=node.dataset.term,id=node.dataset.id,c=context();
 switch(name){
  case 'navigate':navigate(node.dataset.view);break;
  case 'close-modal':modal.close();pendingImport=null;break;
  case 'menu':root.querySelector('.app-shell').classList.toggle('menu-open');break;
  case 'close-menu':root.querySelector('.app-shell').classList.remove('menu-open');break;
  case 'manage-apps':manageApps();break;
  case 'add-competitor':manageApps(true);break;
  case 'switch-app':db.select(id,c.country);modal.close();selectedTerm='';render();if(!db.current.metadata.checkedAt)await job('读取所选地区的应用资料…',()=>refreshMetadata(id,c.country));break;
  case 'pick-app':{const a=modalResults.find(x=>x.id===id);if(!a)throw new Error('请重新搜索后选择 App。');if(node.dataset.role==='competitor')addCompetitor(a);else{db.addApp({...a,checkedAt:new Date().toISOString()},c.country);modal.close();selectedTerm='';render();toast('已添加 App，可在设置中校准产品特征。');}}break;
  case 'add-known-competitor':{const a=candidateById(id);if(a)addCompetitor(a);else throw new Error('找不到这条公开 App 资料，请重新查询。');}break;
  case 'remove-competitor':c.sc.competitors=c.sc.competitors.filter(x=>x.id!==id);db.save();render();break;
  case 'refresh-competitor':await job('读取竞品公开资料…',async()=>{const x=await provider.lookup(id,c.country,true),i=c.sc.competitors.findIndex(x=>x.id===id),before=candidateById(id);if(i>=0)c.sc.competitors[i]={...x.app,subtitle:before?.subtitle??''};else modalResults.push(x.app);db.save();toast('已读取竞品公开资料。');});break;
  case 'refresh-app':await job('更新当前应用资料…',async()=>{await refreshMetadata(c.app.id,c.country);toast('应用公开资料已更新。');});break;
  case 'app-details':showModal('公开产品描述',`<p class="muted small">${V.time(c.app.checkedAt??seed.checkedAt)}</p><pre>${e(c.app.description||'该源未返回描述。')}</pre>`);break;
  case 'select-word':selectedTerm=term;render();break;
  case 'track':{const w=db.addWord(term);w.tracked=!w.tracked;db.save();render();}break;
  case 'add-candidate':db.addWord(term);selectedTerm=term;render();toast('已加入待研究候选，尚未自动获得搜索数据。');break;
  case 'add-words':showModal('添加关键词',`<form id="words-form" class="modal-form"><label>每行一个词，或使用英文逗号分隔<textarea name="terms" rows="7" required placeholder="akari puzzle\nlight up puzzle"></textarea></label><label class="inline-check"><input type="checkbox" name="track">同时加入关注列表</label><button type="submit" class="primary">加入候选词表</button></form>`);break;
  case 'query-one':await queryTerms([term]);break;
  case 'query-batch':await queryTerms(Object.values(c.sc.words).filter(x=>(!filter||x.term.includes(filter))&&(!trackedOnly||x.tracked)).map(x=>x.term));break;
  case 'query-tracked':await queryTerms(Object.values(c.sc.words).filter(x=>x.tracked).map(x=>x.term));break;
  case 'results':details(term);break;
  case 'to-composer':targetWord=term;navigate('composer');break;
  case 'import-words':pickFile('words');break;
  case 'export-words':download(`${safeName(c.app.name)}-${c.country}-keywords.csv`,csvWords(),'text/csv;charset=utf-8');break;
  case 'propose-draft':{const d=draftProposal(c.app,c.sc.profile,c.draft,locale);showModal('审阅规则候选',`<div class="notice">当前是规则模板，不是模型生成。补充词的搜索需求尚需验证；应用后仍然只是本地草稿。</div><dl class="definition"><dt>标题</dt><dd>${e(d.title)} (${charCount(d.title)} / 30)</dd><dt>副标题</dt><dd>${e(d.subtitle)} (${charCount(d.subtitle)} / 30)</dd><dt>关键词</dt><dd>${e(d.keywords)}</dd><dt>依据</dt><dd>${e(d.notes)}</dd></dl><div class="modal-footer">${V.button('保留当前草稿','close-modal')}${V.button('应用到本地草稿','apply-proposal','primary')}</div>`);pendingImport={mode:'proposal',draft:d,scope:{...db.selection,locale}};}break;
  case 'apply-proposal':{const x=pendingImport;if(x?.mode!=='proposal')break;db.state.scopes[scopeKey(x.scope.appId,x.scope.country)].drafts[x.scope.locale]={...x.draft,savedAt:new Date().toISOString()};db.save();pendingImport=null;modal.close();render();toast('规则候选已保存为本地草稿。');}break;
  case 'export-draft':exportDraft();break;
  case 'export-locales':exportDraft(true);break;
  case 'copy-draft':try{await navigator.clipboard.writeText(`TITLE\n${c.draft.title}\n\nSUBTITLE\n${c.draft.subtitle}\n\nKEYWORDS\n${c.draft.keywords}`);toast('已复制到剪贴板。');}catch{exportDraft();toast('剪贴板不可用，已改为下载文案。');}break;
  case 'log-experiment':showModal('记录一次文案实验',`<form id="experiment-form" class="modal-form"><label>版本 / 实验名称<input name="version" placeholder="例如 1.0.4 · Akari 标题实验"></label><label>计划发布日期<input name="releaseDate" type="date"></label><label>需要验证的假设<textarea name="hypothesis" required>${e(c.draft.notes||'')}</textarea></label><button type="submit" class="primary">保存实验与文案快照</button></form>`);break;
  case 'experiments':showExperiments();break;
  case 'restore-experiment':{const x=c.sc.experiments.find(x=>x.id===id);if(x){locale=x.locale;c.sc.drafts[locale]={...x.draft,savedAt:new Date().toISOString()};db.save();modal.close();navigate('composer');toast('已恢复该实验的文案草稿。');}}break;
  case 'open-locale':locale=node.dataset.locale;navigate('composer');break;
  case 'refresh-chart':await job('读取 Apple 公开榜单…',async()=>{const x=await provider.chart(c.country,chartType,true);chartCache.set(c.country+'|'+chartType,x);toast(x.warning??'榜单已更新。');});break;
  case 'refresh-reviews':await job('读取当前地区公开评论…',async()=>{const r=await provider.reviews(c.app.id,c.country);reviewsCache.set(scopeKey(c.app.id,c.country),r);toast(r.warning??`当前 Feed 返回 ${r.results.length} 条文字评论。`);});break;
  case 'import-popularity':pickFile('popularity');break;
  case 'popularity-template':download('apple-ads-popularity-template.csv',toCSV([['searchTerm','countryOrRegion','searchPopularity1to100','month']]),'text/csv;charset=utf-8');toast('模板没有示例分值；请填入自己的实际报告数据。');break;
  case 'import-analytics':pickFile('analytics');break;
  case 'analytics-template':download('analytics-template.csv',toCSV([['date','impressions','pageViews','downloads']]),'text/csv;charset=utf-8');break;
  case 'analytics-detail':showModal('本地报表明细',`<p class="muted small">当前 App ${e(c.app.name)} · ${e(c.country.toUpperCase())}</p><div class="table-scroll"><table><thead><tr><th>日期</th><th>曝光</th><th>访问</th><th>下载</th></tr></thead><tbody>${c.sc.analytics.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(r=>`<tr><td>${e(r.date)}</td><td>${r.impressions}</td><td>${r.pageViews}</td><td>${r.downloads}</td></tr>`).join('')}</tbody></table></div>`);break;
  case 'popularity-detail':{const vals=Object.values(db.state.popularity).filter(x=>x.country===c.country);showModal('已导入的相对热度',vals.length?`<div class="table-scroll"><table><thead><tr><th>词</th><th>地区</th><th>热度</th><th>周期</th><th>来源</th></tr></thead><tbody>${vals.map(x=>`<tr><td>${e(x.term)}</td><td>${e(x.country.toUpperCase())}</td><td>${x.score}</td><td>${e(x.period)}</td><td>${e(x.source)}</td></tr>`).join('')}</tbody></table></div>`:V.empty('尚未导入热度','需要自己获得的有效 Apple Ads 数据。'));}break;
  case 'backup':download(`aso-desk-backup-${new Date().toISOString().slice(0,10)}.json`,db.export(),'application/json');toast('已导出本地工作台备份。');break;
  case 'restore':pickFile('restore','.json,application/json');break;
  case 'apply-import':{const x=pendingImport;if(!x)break;const sc=db.state.scopes[scopeKey(x.scope.appId,x.scope.country)];if(x.mode==='popularity'){db.state.popularityHistory??={};for(const v of x.values){const k=v.country+'|'+v.term;db.state.popularityHistory[k]=appendPopularity(db.state.popularityHistory[k],v);db.state.popularity[k]=popularityTrend(db.state.popularityHistory[k]).latest;}}else if(x.mode==='analytics'){sc.analytics=x.values;sc.analyticsSource={name:x.filename,importedAt:new Date().toISOString()};}else if(x.mode==='words'){for(const v of x.values){if(!Object.hasOwn(sc.words,v.term))sc.words[v.term]={term:v.term,tracked:false};}}db.save();pendingImport=null;modal.close();render();toast('已导入有效数据并保存本机。');}break;
  case 'apply-restore':{const x=pendingImport;if(x?.mode==='restore'){db.restore(x.text);selectedTerm='';modal.close();pendingImport=null;render();toast('备份已恢复。');}}break;
 }
}
document.addEventListener('click',async ev=>{const b=ev.target.closest('[data-action]');if(!b||b.disabled)return;ev.preventDefault();try{await action(b.dataset.action,b);}catch(error){report(error);}});
document.addEventListener('input',ev=>{
 const t=ev.target;if(t.dataset.draft){const d=getDraft();d[t.dataset.draft]=t.value;const c=context();const checks=document.querySelector('#draft-checks');if(checks)checks.innerHTML=V.draftChecks(c);['title','subtitle','keywords'].forEach(f=>{const n=document.querySelector('#count-'+f);if(n){const max=f==='keywords'?100:30;n.textContent=charCount(d[f])+' / '+max;n.className='number '+(charCount(d[f])>max?'red':'green');}});const bytes=document.querySelector('#keyword-bytes');if(bytes)bytes.textContent='UTF-8 字节 '+byteCount(d.keywords);clearTimeout(saveTimer);saveTimer=setTimeout(saveDraft,350);}
 if(t.id==='word-filter'){filter=normalize(t.value);document.querySelector('#word-table').innerHTML=V.tableOnly(context());}
});
document.addEventListener('change',async ev=>{const t=ev.target;try{
 if(t.id==='country'){const id=db.selection.appId;db.select(id,t.value);selectedTerm='';filter='';render();await job('查询所选地区的应用资料…',()=>refreshMetadata(id,t.value));}
 if(t.id==='word-sort'){sort=t.value;render();}if(t.id==='tracked-only'){trackedOnly=t.checked;render();}
 if(t.id==='draft-locale'){saveDraft();locale=t.value;render();}
 if(t.id==='history-word'){selectedTerm=t.value;render();}
 if(t.id==='chart-type'){chartType=t.value;render();}
 if(t.id==='trend-relevant'){trendRelevantOnly=t.checked;render();}
}catch(error){report(error);}});
document.addEventListener('submit',async ev=>{ev.preventDefault();const f=ev.target,x=new FormData(f);try{
 if(f.id==='profile-form'){const sc=db.current;sc.profile={kind:x.get('kind'),features:String(x.get('features')).split(/[,，\n]/).map(normalize).filter(Boolean),seeds:String(x.get('seeds')).split('\n').map(normalize).filter(Boolean)};sc.metadata.subtitle=String(x.get('subtitle'));sc.metadata.subtitleSource='用户从公开商店页面手动导入';db.save();render();toast('已保存产品特征与副标题。');}
 if(f.id==='words-form'){const terms=String(x.get('terms')).split(/[,，\n]/).map(normalize).filter(Boolean);for(const term of terms){const w=db.addWord(term);if(x.get('track'))w.tracked=true;}db.save();modal.close();selectedTerm=terms[0]??selectedTerm;render();toast('已加入 '+terms.length+' 个候选词。');}
 if(f.id==='app-search-form'){const input=String(x.get('query')).trim(),id=appId(input),country=db.selection.country,role=String(x.get('role'));const b=f.querySelector('button[type=submit]');b.disabled=true;b.textContent='正在查询…';try{if(id){const result=await provider.lookup(id,country);modalResults=[{...result.app,checkedAt:result.checkedAt}];}else{if(input.length<2)throw new Error('名称查询至少输入两个字符。');const result=await provider.search(input,country,50);modalResults=result.data.results.map(normalizeApp);}showModal('选择正确的 '+(role==='competitor'?'竞品':'App'),modalResults.length?V.resultsList(modalResults,{action:'pick-app',label:role==='competitor'?'加入比较':'添加 App'}):V.empty('没有返回结果','换一个名称或检查当前地区。'));modal.querySelectorAll('[data-action="pick-app"]').forEach(b=>b.dataset.role=role);}catch(error){b.disabled=false;b.textContent='查询公开 App 资料';throw error;}}
 if(f.id==='experiment-form'){const sc=db.current;sc.experiments.push({id:crypto.randomUUID(),locale,version:String(x.get('version')),releaseDate:String(x.get('releaseDate')),hypothesis:String(x.get('hypothesis')),draft:structuredClone(getDraft()),createdAt:new Date().toISOString()});db.save();showExperiments();toast('实验与文案快照已保存。');}
}catch(error){report(error);}});
fileInput.addEventListener('change',async()=>{const f=fileInput.files[0];if(!f)return;try{if(f.size>5*1024*1024)throw new Error('文件超过 5 MB，请拆分或减少无关内容后导入。');const text=await f.text();if(fileMode==='restore'){const parsed=JSON.parse(text);if(parsed.schema!==1||!parsed.apps||!parsed.scopes)throw new Error('不是有效的 ASO Desk 备份。');pendingImport={mode:'restore',text};showModal('审阅备份恢复',`<div class="notice amber">导入会替换当前本机工作台。建议先导出当前资料；备份内容不会上传到服务器。</div><p>${Object.keys(parsed.apps).length} 个 App · ${Object.keys(parsed.scopes).length} 个 App / 地区工作区</p><div class="modal-footer">${V.button('先导出当前备份','backup')}${V.button('取消','close-modal')}${V.button('恢复这份备份','apply-restore','primary')}</div>`);return;}let result;if(fileMode==='popularity')result=importPopularity(text,fileScope.country);else if(fileMode==='analytics')result=importAnalytics(text);else{const rows=parseCSV(text),h=rows[0]?.map(normalize)??[],index=h.findIndex(x=>['keyword','term','searchterm','关键词','搜索词'].includes(x));const data=index<0?rows:rows.slice(1),j=index<0?0:index,errors=[],values=[];data.forEach((r,i)=>{const term=normalize(r[j]);if(!term||term.length>160||['__proto__','constructor','prototype'].includes(term)){errors.push('第 '+(i+1)+' 行关键词无效。');return;}values.push({term});});result={values,errors};}importPreview(fileMode==='popularity'?'审阅热度导入':fileMode==='analytics'?'审阅报表导入':'审阅词表导入',{...result,mode:fileMode,scope:fileScope,filename:f.name},`${f.name} · ${result.values.length} 行有效数据。${fileMode==='analytics'?'将替换当前 App / 地区的本地报表。':'数据仅保存本机。'}`);}catch(error){report(error);}});
window.addEventListener('hashchange',()=>{view=location.hash.slice(1)||'keywords';filter='';render();window.scrollTo({top:0});});
window.addEventListener('pagehide',()=>{if(db)db.save();});
window.addEventListener('storage',ev=>{if(ev.key==='aso-desk.workspace.v1'&&ev.newValue){try{const x=JSON.parse(ev.newValue);if(x.schema===1){db.state=x;render();}}catch{}}});
async function boot(){try{const r=await fetch('data/public.json',{cache:'no-cache'});if(!r.ok)throw new Error('公开数据快照未能加载。');seed=await r.json();db=new Workspace(seed);provider=new AppleProvider(seed);view=location.hash.slice(1)||'keywords';render();}catch(error){root.innerHTML=`<div class="boot"><h1>ASO Desk</h1><p>${e(error.message)}</p><p class="muted">请通过网站地址访问，或启动本地 HTTP 服务；直接双击 HTML 不支持模块加载。</p></div>`;}}
boot();
