import { normalize, addHistory, inferProfile } from './engine.js';
const KEY='aso-desk.workspace.v1';
const newer=(a,b)=>new Date(a??0).getTime()>new Date(b??0).getTime();
export const scopeKey=(id,country)=>String(id)+':'+country;
export class Workspace {
 constructor(seed){this.seed=seed;this.error=null;try{this.state=JSON.parse(localStorage.getItem(KEY)||'null');}catch{this.error='本地存档无法读取，当前使用公开快照；原始存档仍保留。';}if(!this.state||this.state.schema!==1)this.state={schema:1,apps:{},scopes:{},popularity:{},selection:{appId:seed.apps[0].id,country:'us'},preferences:{}};this.mergeSeed(seed);}
 mergeSeed(seed){for(const app of seed.apps){this.state.apps[app.id]??=app;for(const country of Object.keys(app.storefronts??{us:app})){const m=app.storefronts?.[country]??app;const sc=this.ensure(app.id,country,m);if(!sc.metadata.checkedAt||newer(m.checkedAt,sc.metadata.checkedAt))sc.metadata={...m,subtitle:sc.metadata.subtitleSource?.startsWith('用户')?sc.metadata.subtitle:m.subtitle,country};for(const record of seed.searches??[]){if(record.appId!==app.id||record.country!==country)continue;const t=normalize(record.term);if(!Object.hasOwn(sc.words,t))sc.words[t]={term:t,tracked:false};const remote=seed.histories?.[[app.id,country,t].join('|')]??[];for(const point of remote){sc.words[t].history=addHistory(sc.words[t].history,{...point,status:'ok'});}if(!sc.words[t].record||newer(record.checkedAt,sc.words[t].record.checkedAt)){sc.words[t].record=record;sc.words[t].history=addHistory(sc.words[t].history,record);}}}}}
 ensure(id,country,metadata){const k=scopeKey(id,country),base=this.state.apps[id];if(this.state.scopes[k])return this.state.scopes[k];const known=metadata??base?.storefronts?.[country];const m=known?{...known,country}:{id:String(id),name:base?.name??'App '+id,description:base?.description??'',category:base?.category??'',genres:base?.genres??[],icon:base?.icon??'',developer:base?.developer??'',subtitle:'',rating:null,ratingCount:null,version:'',checkedAt:null,country,countryUnverified:true};return this.state.scopes[k]={metadata:m,profile:inferProfile(m),words:{},competitors:[],drafts:{},experiments:[],analytics:[],updatedAt:null};}
 get selection(){return this.state.selection;}
 get current(){return this.ensure(this.selection.appId,this.selection.country);}
 save(){try{localStorage.setItem(KEY,JSON.stringify(this.state));this.error=null;return true;}catch{this.error='本机存储空间不足或被浏览器禁用；当前修改仅保留在本页，请立即导出备份。';return false;}}
 update(fn){fn(this.state);this.save();}
 addApp(app,country){this.state.apps[app.id]??=app;const sc=this.ensure(app.id,country,app);sc.metadata=app;sc.profile=inferProfile(app);this.state.selection={appId:app.id,country};this.save();}
 select(id,country){this.state.selection={appId:String(id),country};this.ensure(id,country);this.save();}
 addWord(term){const t=normalize(term);if(!t||t.length>160||['__proto__','constructor','prototype'].includes(t))throw new Error('关键词无效；请输入 1–160 字符的普通搜索词。');if(!Object.hasOwn(this.current.words,t))this.current.words[t]={term:t,tracked:false};this.save();return this.current.words[t];}
 record(record){const key=scopeKey(record.appId,record.country),sc=this.state.scopes[key];if(!sc)throw new Error('查询所属的 App / 地区不存在。');const t=normalize(record.term);sc.words[t]??={term:t,tracked:false};sc.words[t].record=record;if(record.status==='ok')sc.words[t].history=addHistory(sc.words[t].history,record);sc.updatedAt=record.checkedAt;this.save();}
 export(){return JSON.stringify({...this.state,exportedAt:new Date().toISOString()},null,2);}
 restore(text){const x=JSON.parse(text);if(x.schema!==1||!x.apps||!x.scopes||!x.selection||!x.popularity)throw new Error('不是有效的 ASO Desk 备份。');if(!x.apps[x.selection.appId]||!x.scopes[scopeKey(x.selection.appId,x.selection.country)])throw new Error('备份缺少选中的 App / 地区。');for(const [k,s] of Object.entries(x.scopes)){if(!s.metadata?.id||typeof s.metadata.name!=='string'||!s.words||!s.drafts||!s.profile||!Array.isArray(s.profile.features)||!Array.isArray(s.profile.seeds)||!Array.isArray(s.competitors)||!Array.isArray(s.experiments)||!Array.isArray(s.analytics))throw new Error('备份中的工作区结构无效：'+k);for(const [t,w] of Object.entries(s.words)){if(['__proto__','constructor','prototype'].includes(t)||typeof w.term!=='string'||w.history&&!Array.isArray(w.history))throw new Error('备份关键词结构无效。');}for(const d of Object.values(s.drafts))if(['title','subtitle','keywords'].some(f=>typeof d[f]!=='string'))throw new Error('备份文案结构无效。');}for(const p of Object.values(x.popularity))if(typeof p.score!=='number'||p.score<1||p.score>100||typeof p.term!=='string'||typeof p.country!=='string')throw new Error('备份热度数据无效。');this.state=x;this.save();}
}
