import {escapeHTML as e,safeURL,COUNTRIES,LOCALES,relevance,actionFor,competition,coverage,analyzeDraft,historyDelta,tokens,stem,charCount,inferProfile,popularityTrend} from './engine.js';
export const NAV={overview:['概览','grid'],keywords:['关键词研究','trend'],competitors:['竞品洞察','people'],composer:['文案工作室','edit'],history:['排名监测','chart'],locales:['本地化','globe'],charts:['分类榜单','list'],trends:['搜索趋势','trend'],reviews:['评论与转化','star'],settings:['数据与设置','settings']};
export function icon(n){const paths={grid:'M3 3h18v18H3z M3 9h18 M3 15h18 M9 3v18 M15 3v18',trend:'M3 18l6-7 5 3 7-10 M15 4h6v6',edit:'M4 16L16 4l4 4L8 20H4z M13 7l4 4',people:'M8 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M3 21v-4q5-7 10 0v4 M17 12a3 3 0 1 0 0-6 M17 15q5-2 5 6',chart:'M4 3h16v18H4z M8 8h8 M8 13h8 M8 18h4',globe:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20 M2 12h20 M12 2q-8 10 0 20 M12 2q8 10 0 20',list:'M8 5h13 M8 12h13 M8 19h13 M3 5h1 M3 12h1 M3 19h1',star:'M12 3l3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M4 4l16 16 M4 20L20 4 M12 2v4 M12 18v4 M2 12h4 M18 12h4',menu:'M3 5h18 M3 12h18 M3 19h18'};return `<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]??paths.grid}"/></svg>`;}
export const badge=(t,color='')=>`<span class="badge ${color}">${e(t)}</span>`;
export const button=(t,action,cls='',data='')=>`<button class="${cls}" data-action="${action}" ${data}>${e(t)}</button>`;
export function appIcon(app){return `<span class="icon-box" aria-hidden="true">${e(app.name?.[0]??'A')}${safeURL(app.icon)?`<img src="${e(safeURL(app.icon))}" alt="" loading="lazy" referrerpolicy="no-referrer">`:''}</span>`;}
export function time(t){return t&&Number.isFinite(new Date(t).getTime())?new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Shanghai'}).format(new Date(t))+' 北京时间':'尚未查询';}
export const empty=(title,message,action,label)=>`<div class="empty">${icon('grid')}<h3>${e(title)}</h3><p>${e(message)}</p>${action?button(label,action,'primary'):''}</div>`;
const link=(url,text)=>safeURL(url)?`<a href="${e(safeURL(url))}" target="_blank" rel="noopener noreferrer">${e(text)} ↗</a>`:e(text);
const stat=(title,value,note,color='')=>`<div class="panel stat"><div class="muted">${e(title)}</div><div class="value number ${color}">${e(value)}</div><div class="muted">${e(note)}</div></div>`;
export function shell(c,content){
 const {app,db,view,busy}=c;
 return `<div class="app-shell"><div class="menu-scrim" data-action="close-menu"></div><aside class="sidebar"><a href="#overview" class="logo"><img src="assets/logo.svg" alt="">ASO Desk</a><div class="side-label">个人 ASO 工作台</div><div class="app-switch">${appIcon(app)}<button data-action="manage-apps"><strong>${e(app.name)}</strong><small>管理 App ▾</small></button></div><div class="side-label">增长工具</div><nav aria-label="主导航">${Object.entries(NAV).map(([k,[t,i]])=>`<a class="nav-link ${view===k?'active':''}" href="#${k}" ${view===k?'aria-current="page"':''}>${icon(i)}${t}</a>`).join('')}</nav><div style="min-height:35px;flex:1"></div><div class="privacy-card"><strong class="green small">独立工作台</strong><p>公开数据来自 Apple<br>选词、草稿和报表保存在本机</p>${button('导出工作台备份','backup','ghost small')}</div><div class="version">V1.0 · GitHub Pages</div></aside><main class="workspace"><header class="topbar"><button class="mobile-menu" data-action="menu" aria-label="打开导航">${icon('menu')}</button><span class="crumb">工作台 / ${e(app.name)}</span><select id="country" aria-label="国家或地区">${Object.entries(COUNTRIES).map(([k,v])=>`<option value="${k}" ${k===db.selection.country?'selected':''}>${v} · ${k.toUpperCase()}</option>`).join('')}</select>${button('添加 / 切换 App','manage-apps','add-app')}</header>${db.error?`<div class="notice red section-gap">${e(db.error)} ${button('导出备份','backup')}</div>`:''}${busy?`<div class="busy-strip"><div class="loading" role="status">${e(busy)}</div></div>`:''}${content}<footer class="footer"><span>地区 ${e(db.selection.country.toUpperCase())} · 序位来源：Apple Search API · 草稿仅保存本机</span><span>${link('https://developer.apple.com/app-store/search/','Apple 搜索说明')} · <a href="#settings">数据与备份</a></span></footer></main></div>`;
}
function heading(title,sub,extra=''){return `<div class="heading"><div><h1>${e(title)}</h1><p>${e(sub)}</p></div>${extra?`<div class="toolbar">${extra}</div>`:''}</div>`;}
function wordStats(c){const a=Object.values(c.sc.words),queried=a.filter(w=>w.record?.status==='ok'),found=queried.filter(w=>w.record.position!=null),demand=a.filter(w=>c.db.state.popularity[c.country+'|'+w.term]);return `<div class="stats">${stat('已查询关键词',queried.length,'当前 App / 地区')}${stat('结果中出现',found.length,'其余 '+(queried.length-found.length)+' 个未出现','green')}${stat('关注关键词',a.filter(w=>w.tracked).length,'手动收藏，按地区分别保存')}${stat('已导入热度',demand.length?demand.length:'待接入','官方相对指标需授权或导入','amber')}</div>`;}
function wordTable(c,filtered=true){
 let words=Object.values(c.sc.words);
 if(filtered){words=words.filter(w=>(!c.filter||w.term.includes(c.filter))&&(!c.trackedOnly||w.tracked));if(c.sort==='rank')words.sort((a,b)=>(a.record?.position??999)-(b.record?.position??999));if(c.sort==='popularity')words.sort((a,b)=>(c.db.state.popularity[c.country+'|'+b.term]?.score??-1)-(c.db.state.popularity[c.country+'|'+a.term]?.score??-1));if(c.sort==='relevance')words.sort((a,b)=>({high:0,medium:1,unknown:2,low:3}[relevance(a.term,c.sc.profile).level])-({high:0,medium:1,unknown:2,low:3}[relevance(b.term,c.sc.profile).level]));}
 if(!words.length)return empty('这里还没有关键词','添加产品词、导入 CSV，或从下方候选开始。','add-words','添加关键词');
 return `<div class="table-scroll"><table><thead><tr><th><span class="screen-reader">关注</span></th><th>关键词 / 覆盖来源</th><th>API 序位</th><th>热度</th><th>竞争估算</th><th>相关性</th><th>建议动作</th></tr></thead><tbody>${words.map(w=>{const r=w.record,p=c.db.state.popularity[c.country+'|'+w.term],rel=relevance(w.term,c.sc.profile),comp=competition(r,c.app),a=actionFor(w.term,r,c.sc.profile,c.publicDraft),cov=coverage(w.term,c.publicDraft);return `<tr class="${w.term===c.selectedTerm?'selected':''}"><td><button class="star ${w.tracked?'tracked':''}" data-action="track" data-term="${e(w.term)}" aria-label="${w.tracked?'取消关注':'关注'} ${e(w.term)}" aria-pressed="${w.tracked}">${w.tracked?'★':'☆'}</button></td><td><button class="term" data-action="select-word" data-term="${e(w.term)}">${e(w.term)}</button><small>${cov.title?'标题':cov.subtitle?'副标题':cov.keywords?'导入的关键词字段':'候选词'} · ${r?.status==='ok'?time(r.checkedAt):r?.status==='error'?'查询失败':'未查询'}</small></td><td>${r?.status==='ok'?(r.position==null?badge('未出现'): `<span class="rank number">${r.position}</span>`):badge(r?.status==='error'?'源错误':'—',r?.status==='error'?'red':'')}</td><td class="number">${p?`<strong>${e(p.score)}</strong><small>${e(p.period)}</small>`:'<span class="muted">—</span>'}</td><td>${comp?`<strong class="number">${comp.score}</strong><small>估算 · 前 ${comp.sampleSize} 个</small>`:'<span class="muted">—</span>'}</td><td>${badge(rel.label,rel.level==='high'?'green':rel.level==='low'?'amber':'')}</td><td><button class="ghost small" data-action="select-word" data-term="${e(w.term)}">${e(a.label)} →</button></td></tr>`;}).join('')}</tbody></table></div>`;
}
function evidence(c){
 const w=c.sc.words[c.selectedTerm];if(!w)return `<aside class="panel reason-card">${empty('选择一个词','查看搜索结果、相关性和建议依据。')}</aside>`;
 const r=w.record,rel=relevance(w.term,c.sc.profile),action=actionFor(w.term,r,c.sc.profile,c.publicDraft),comp=competition(r,c.app),demand=c.db.state.popularity[c.country+'|'+w.term];
 return `<aside class="panel reason-card">${badge('当前分析 · '+w.term,'green')}<h2>先确认词意，再争取曝光</h2><div class="reason-block"><h3>玩法契合 · ${e(rel.label)}</h3><p>${e(rel.reason)}</p></div><div class="reason-block"><h3>搜索证据</h3><p>${r?.status==='ok'?`本次返回 ${r.returned} 个结果；${r.position==null?'没有找到当前 App。':'当前 App 的 API 序位为 '+r.position+'。'}`:r?.status==='error'?e(r.error):'尚未查询，当前没有位置证据。'}</p><p class="muted small">${r?.sourceURL?link(r.sourceURL,'原始来源'):''}</p></div><div class="reason-block"><h3>下一步 · ${e(action.label)}</h3><p>${e(action.reason)}</p></div><div class="toolbar">${button('查询这个词','query-one','primary',`data-term="${e(w.term)}"`)}${r?.status==='ok'?button('查看头部结果','results','',`data-term="${e(w.term)}"`):''}${button('带入文案 →','to-composer','ghost',`data-term="${e(w.term)}"`)}</div><p class="evidence-note">${demand?'热度来源：'+e(demand.source)+'，'+e(demand.period):'热度未导入；不会用默认数值补齐。'}${comp?'<br>'+e(comp.explanation):''}</p></aside>`;
}
export function keywords(c){
 const pool=[...new Set([...(c.sc.profile.seeds??[]),...(c.sc.profile.features??[])])].filter(t=>!c.sc.words[t]).slice(0,22);
 return `${heading('找到值得争取的搜索词','从产品相关性、公开搜索结果和竞品覆盖，决定下一步。')}${wordStats(c)}<div class="two-col"><section class="panel"><div class="panel-head"><h2>关键词证据库 ${badge('搜索 API 序位','blue')}</h2><div class="toolbar">${button('添加关键词','add-words')}${button('批量查询','query-batch','primary')}</div></div><div class="toolbar"><input id="word-filter" class="search" placeholder="搜索已有关键词…" value="${e(c.filter)}" aria-label="筛选关键词"><select id="word-sort" aria-label="排序"><option value="relevance" ${c.sort==='relevance'?'selected':''}>相关性优先</option><option value="rank" ${c.sort==='rank'?'selected':''}>序位</option><option value="popularity" ${c.sort==='popularity'?'selected':''}>热度</option></select><label class="inline-check small"><input id="tracked-only" type="checkbox" ${c.trackedOnly?'checked':''}>仅关注</label>${button('导入 CSV','import-words','ghost small')}${button('导出','export-words','ghost small')}</div><div id="word-table">${wordTable(c)}</div><p class="evidence-note">最多查询 200 个返回结果。“未出现”不等于没有需求；API 序位可能与设备内 App Store 不同。批量查询按约 4 秒一次节流。</p></section>${evidence(c)}</div><section class="panel section-gap"><h2>按产品意图扩展候选词</h2><p class="muted small section-gap">来自已确认的产品特征；竞品词可在覆盖对比页单独加入。候选没有自动获得热度或排名证据。</p><div class="candidates">${pool.map(t=>button(t,'add-candidate','candidate',`data-term="${e(t)}"`)).join('')||'<span class="muted">候选已加入；可在设置中调整产品特征。</span>'}</div></section>`;
}
export function overview(c){
 const rel=Object.values(c.sc.words).filter(w=>relevance(w.term,c.sc.profile).level==='high'),d=analyzeDraft(c.publicDraft,c.locale,c.app.category);
 return `${heading('让每次 ASO 改动都有依据','研究关键词 → 校准竞品 → 组织文案 → 记录实验。',button('更新应用资料','refresh-app'))}${wordStats(c)}<div class="two-even"><section class="panel"><div class="panel-head"><h2>当前公开商店资料</h2>${link(c.app.url,'App Store')}</div><div class="app-line toolbar">${appIcon(c.app)}<div><h2>${e(c.app.name)}</h2><p class="muted">${e(c.app.subtitle||'副标题未读取，可在数据设置中手动导入')}</p></div></div><dl class="definition"><dt>版本 / 分类</dt><dd>${e(c.app.version||'—')} / ${e(c.app.category||'—')}</dd><dt>评分</dt><dd>${c.app.ratingCount?Number(c.app.rating).toFixed(2)+' · '+c.app.ratingCount+' 条评分':'当前无评分或该源未返回评分'}</dd><dt>开发者</dt><dd>${e(c.app.developer||'—')}</dd><dt>资料时间</dt><dd>${time(c.sc.metadata.checkedAt??c.seed.checkedAt)}</dd></dl>${button('查看完整公开描述','app-details','ghost')}</section><section class="panel reason-card"><h2>优先处理的三件事</h2><div class="reason-block"><h3>01 · 校准产品特征</h3><p>当前类型：${e(c.sc.profile.kind)}。调整功能与场景词，减少不相关推荐。</p></div><div class="reason-block"><h3>02 · 验证核心候选</h3><p>当前 ${rel.length} 个高相关词。先查询并检查头部 App，再扩展范围。</p></div><div class="reason-block"><h3>03 · 检查字段分工</h3><p>当前已知字段有 ${d.issues.filter(x=>x.level!=='info').length} 条待检查项；隐藏关键词字段需要自行导入。</p></div><div class="toolbar">${button('开始关键词研究','navigate','primary','data-view="keywords"')}${button('查看文案','navigate','','data-view="composer"')}</div></section></div><section class="panel section-gap"><div class="panel-head"><h2>数据覆盖</h2>${button('导入热度 / 报表','navigate','','data-view="settings"')}</div><div class="cards-three"><div><h3 class="green">公开数据</h3><p class="muted small section-gap">应用资料、搜索结果、榜单、评论。每次查询记录地区、来源和时间。</p></div><div><h3 class="amber">授权热度</h3><p class="muted small section-gap">先支持导入 Apple Ads 周/月相对热度；暂无已绑定的官方账户。</p></div><div><h3 class="blue">本地工作资料</h3><p class="muted small section-gap">选词、文案草稿、实验、报表存在当前浏览器。跨设备使用前导出 JSON 备份。</p></div></div></section>`;
}
export function competitors(c){
 const selected=c.sc.competitors;
 const candidates=[...new Map(Object.values(c.sc.words).flatMap(w=>w.record?.topResults??[]).filter(x=>x.id!==c.app.id&&x.category===c.app.category).map(x=>[x.id,x])).values()].filter(x=>!selected.some(s=>s.id===x.id)).slice(0,8);
 const displayed=selected.length?selected:candidates.slice(0,3),all=[c.app,...displayed];
 const terms=[...new Set(displayed.flatMap(x=>tokens(x.name+' '+(x.subtitle??'')).map(stem)).filter(t=>t.length>2&&!['your','the','and','with','game','app'].includes(t)))].slice(0,20);
 return `${heading('看清与你争夺同一意图的 App','同分类仅是候选线索；请确认玩法相同，再将其纳入长期比较。',button('按 App ID / 名称添加','add-competitor','primary'))}${!selected.length?'<div class="notice">下方是根据当前搜索结果筛选的同分类候选，尚未加入你的竞品列表。</div>':''}<div class="cards-three">${displayed.map(a=>`<section class="panel competitor-card"><div class="app-line">${appIcon(a)}<div>${badge(selected.length?'已选竞品':'同类候选')}<p>App ID ${e(a.id)}</p></div></div><h3>${e(a.name)}</h3><p>${e(a.subtitle||'该源未返回副标题')}<br>评分 ${a.rating==null?'未知':Number(a.rating).toFixed(2)} · ${a.ratingCount??'未知'} 条评分</p>${link(a.url,'App Store')}<div class="card-actions">${selected.some(x=>x.id===a.id)?button('移出比较','remove-competitor','ghost',`data-id="${e(a.id)}"`):button('加入比较','add-known-competitor','primary',`data-id="${e(a.id)}"`)}${button('刷新公开资料','refresh-competitor','ghost',`data-id="${e(a.id)}"`)}</div></section>`).join('')||`<section class="panel">${empty('还没有竞品证据','先查询关键词，或按名称 / ID 添加同类 App。','add-competitor','添加竞品')}</section>`}</div>${displayed.length?`<div class="two-col section-gap"><section class="panel"><h2>公开标题 / 已导入副标题覆盖</h2><p class="muted small section-gap">词形统一后比较，原始文案保留。竞品隐藏关键词不可公开读取。</p><div class="table-scroll"><table><thead><tr><th>词 / 词形</th>${all.map(a=>`<th title="${e(a.name)}">${e(a.name.slice(0,17))}</th>`).join('')}<th>研究</th></tr></thead><tbody>${terms.map(t=>`<tr><td>${e(t)}</td>${all.map(a=>`<td>${tokens(a.name+' '+(a.subtitle??'')).map(stem).includes(t)?'<span class="green">●</span>':'<span class="muted">—</span>'}</td>`).join('')}<td>${button('加入候选','add-candidate','ghost small',`data-term="${e(t)}"`)}</td></tr>`).join('')}</tbody></table></div></section><aside class="panel"><h2>把差距变成实验</h2><div class="reason-block"><h3>同类词不等于适合你</h3><p>竞品出现的词先进入候选；研究其对应的玩法和搜索意图。</p></div><div class="reason-block"><h3>低评分量不等于低竞争</h3><p>竞争代理还考虑公开标题匹配与同分类比例，不推断真实下载量。</p></div><div class="reason-block"><h3>你的副标题也算覆盖</h3><p>${e(c.app.subtitle||'副标题尚未读取，请在设置中手动导入。')}</p></div>${button('查看关键词证据','navigate','primary','data-view="keywords"')}</aside></div>`:''}${candidates.length?`<section class="panel section-gap"><div class="panel-head"><h2>其他同类候选</h2></div>${resultsList(candidates,{action:'add-known-competitor',label:'加入比较'})}</section>`:''}`;
}
export function draftChecks(c){const report=analyzeDraft(c.draft,c.locale,c.app.category);return `<div class="checklist">${report.issues.length?report.issues.map(i=>`<div class="check-item"><span class="${i.level==='error'?'red':i.level==='info'?'blue':'amber'}">${i.level==='error'?'×':'○'}</span><div>${e(i.message)}</div></div>`).join(''):'<div class="check-item"><span class="green">✓</span><div>字段容量与常见重复检查通过<small>不代表搜索效果已验证，关键词仍需研究。</small></div></div>'}<div class="check-item"><span class="blue">i</span><div>产品事实需要人工确认<small>规则只检查文案格式与词覆盖，不保证排名提升。</small></div></div><div class="check-item"><span class="amber">○</span><div>隐藏关键词字段${c.draft.keywords?'为本地草稿':'尚未导入'}<small>页面不能从公开资料获取自己的隐藏字段。</small></div></div></div>`;}
export function composer(c){
 const d=c.draft;return `${heading('每一个字符，都有明确用途','对照公开商店文案，规划核心词、补充词与下一次实验。')}<div class="draft-banner"><div><strong class="green">${e(LOCALES[c.locale]??c.locale)} · 本地文案草稿</strong><small>保存于此浏览器；没有写入 App Store Connect。</small></div><div class="toolbar">${button('生成规则候选','propose-draft')}${button('导出文案','export-draft','primary')}</div></div><div class="two-col"><div class="stack"><section class="panel"><div class="panel-head"><h2>商店文案</h2><select id="draft-locale" aria-label="文案语言">${Object.entries(LOCALES).map(([k,v])=>`<option value="${k}" ${c.locale===k?'selected':''}>${v} · ${k}</option>`).join('')}</select></div>${['title','subtitle','keywords'].map((f,i)=>`<label class="field"><span class="field-label"><span>${['标题','副标题','关键词字段'][i]}</span><span id="count-${f}" class="number ${charCount(d[f])>(f==='keywords'?100:30)?'red':'green'}">${charCount(d[f])} / ${f==='keywords'?100:30}</span></span>${f==='keywords'?`<textarea id="draft-${f}" data-draft="${f}" rows="3" placeholder="导入现有隐藏关键词，或填写本地候选…">${e(d[f])}</textarea>`:`<input id="draft-${f}" data-draft="${f}" value="${e(d[f])}">`}<small>${f==='title'?'当前公开标题：'+e(c.app.name):f==='subtitle'?'当前公开副标题：'+e(c.app.subtitle||'未读取'):`<span id="keyword-bytes">UTF-8 字节 ${new TextEncoder().encode(d[f]??'').length}</span> · 使用英文逗号分隔，最终容量以 ASC 校验为准。`}</small></label>`).join('')}<label class="field"><span class="field-label">修改原因 / 实验假设</span><textarea id="draft-notes" data-draft="notes" rows="3">${e(d.notes??'')}</textarea></label><div class="draft-meta"><span id="draft-save-status">${d.savedAt?'已保存 '+time(d.savedAt):'输入后自动保存本地'}</span>${button('复制标题、副标题、关键词','copy-draft','ghost small')}</div></section><section class="panel"><div class="panel-head"><h2>产品描述与推广文本</h2>${badge('影响展示与转化')}</div><label class="field"><span class="field-label">推广文本（170 字符）</span><textarea data-draft="promotionalText" rows="3">${e(d.promotionalText??'')}</textarea></label><label class="field"><span class="field-label">描述（4000 字符）</span><textarea data-draft="description" rows="8">${e(d.description??'')}</textarea></label><p class="evidence-note">推广文本不影响关键词搜索排名。描述和素材仍有助于用户理解产品与决定下载。</p></section></div><div class="stack"><aside class="panel"><h2>文案质量检查</h2><div id="draft-checks" class="section-gap">${draftChecks(c)}</div></aside><aside class="panel"><h2>记录实验，再观察结果</h2><p class="muted small section-gap">保存本次假设、拟发布版本与日期；后续对照同来源位置和用户导入的转化报表。</p>${c.targetWord?`<p class="section-gap">当前研究词：${badge(c.targetWord,'green')}</p>`:''}<div class="toolbar section-gap">${button('记录实验','log-experiment','primary')}${button('实验日志','experiments')}</div><p class="evidence-note">发布前后变化还可能受到季节、下载和竞品等影响，不能直接归因于改词。</p></aside></div></div>`;
}
export function historyChart(points){
 const data=(points??[]).filter(x=>x.position!=null);if(data.length<2)return empty(data.length?'已有一份有效快照':'暂无有效位置点',data.length?'至少需要两个日期的有效位置，才能画变化曲线。':'继续采集；未出现、失败不会补成排名 0。');
 const max=Math.max(10,...data.map(x=>x.position)),min=1,w=720,h=220,l=40,r=20,t=15,b=35,span=(w-l-r)/(points.length-1),py=n=>t+(n-min)/(max-min)*(h-t-b);
 const segments=[];let segment=[];points.forEach((p,i)=>{if(p.position==null){if(segment.length)segments.push(segment);segment=[];}else segment.push(`${l+i*span},${py(p.position)}`);});if(segment.length)segments.push(segment);
 return `<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="API 序位随采集日期变化，数字越小位置越靠前；缺失位置处断开">${[1,Math.round(max/2),max].map(n=>`<path class="gridline" d="M${l} ${py(n)}H${w-r}"/><text x="5" y="${py(n)+4}">${n}</text>`).join('')}${segments.map(a=>`<polyline class="series" points="${a.join(' ')}"/>`).join('')}${data.map(p=>`<circle cx="${l+points.indexOf(p)*span}" cy="${py(p.position)}" r="4" fill="#8be4bd"><title>${e(p.date)} · ${p.position}</title></circle>`).join('')}<text x="${l}" y="${h-8}">${e(points[0].date)}</text><text text-anchor="end" x="${w-r}" y="${h-8}">${e(points.at(-1).date)}</text></svg>`;
}
export function history(c){const a=Object.values(c.sc.words).filter(x=>x.tracked),word=c.sc.words[c.selectedTerm]??a[0],points=word?.history??[],delta=historyDelta(points);return `${heading('观察同一渠道的位置变化','手动查询积累本地快照；GitHub Actions 另行采集已配置的公开关键词。',button('查询已关注词','query-tracked','primary'))}<section class="panel"><div class="panel-head"><h2>${word?e(word.term):'尚未选择关键词'} ${badge('API 序位 · UTC 日期','blue')}</h2><select id="history-word" aria-label="历史关键词">${Object.values(c.sc.words).map(w=>`<option value="${e(w.term)}" ${w.term===word?.term?'selected':''}>${e(w.term)}${w.tracked?' ★':''}</option>`).join('')}</select></div>${points.length?`<div class="toolbar">${badge(points.length+' 个日期')} ${badge(delta==null?'变化尚不可判断':delta>0?'较上一日期前进 '+delta:delta<0?'较上一日期后退 '+Math.abs(delta):'与上一日期相同',delta>0?'green':delta<0?'amber':'')}</div>`:''}${historyChart(points)}<div class="table-scroll"><table><thead><tr><th>日期（UTC）</th><th>API 序位</th><th>返回条数</th><th>采集时间</th></tr></thead><tbody>${points.slice().reverse().map(p=>`<tr><td>${e(p.date)}</td><td>${p.position??'未出现'}</td><td>${p.returned}</td><td>${time(p.checkedAt)}</td></tr>`).join('')}</tbody></table></div><p class="evidence-note">同一日期、同一来源保留最新快照；不同地区分开。图表只展示有效位置点，缺失不是位置 0。</p></section><section class="panel section-gap"><div class="panel-head"><h2>已关注关键词</h2>${button('管理关注','navigate','','data-view="keywords"')}</div>${a.length?wordTable({...c,trackedOnly:true,filter:''}):empty('还没有关注词','点击关键词表格中的星标，建立自己的观察列表。')}</section>`;}
export function locales(c){return `${heading('为不同市场规划自己的文案','本地语言草稿独立保存；翻译需要保留玩法事实，并重新验证当地搜索词。')}<div class="notice">目前提供手工编辑和 Akari 产品的规则候选；没有接入模型翻译或商店自动写入。</div><section class="panel"><h2>语言工作区</h2><div class="locales-grid section-gap">${Object.entries(LOCALES).map(([k,v])=>{const d=c.sc.drafts[k],r=d?analyzeDraft(d,k,c.app.category):null;return `<button class="locale-card ${k===c.locale?'active':''}" data-action="open-locale" data-locale="${k}"><strong>${e(v)}</strong><small>${e(k)} · ${d?'已有草稿':'尚未创建'}</small><small>${d?`${charCount(d.title)} / 30 · ${charCount(d.subtitle)} / 30 · ${charCount(d.keywords)} / 100`:'点击开始编辑'}${r?.issues.some(x=>x.level==='error')?' · 超限需修改':''}</small></button>`;}).join('')}</div><div class="toolbar section-gap">${button('导出全部语言草稿','export-locales','primary')}</div></section><section class="panel section-gap"><h2>交叉本地化需要证据</h2><p class="muted section-gap">Apple 没有在这里提供可验证的全部跨语言索引矩阵。本工作台按语言管理覆盖，不把其他站点的地区映射当作官方保证。</p></section>`;}
export function charts(c){const x=c.chart;return `${heading('查看当前地区的分类榜单','榜单是独立的数据来源，不代表搜索词序位。')}<section class="panel"><div class="panel-head"><h2>Apple 公开榜单 ${badge(c.country.toUpperCase(),'blue')}</h2><div class="toolbar"><select id="chart-type" aria-label="榜单类型"><option value="apps-free" ${c.chartType==='apps-free'?'selected':''}>全部应用 · 免费</option><option value="games-free" ${c.chartType==='games-free'?'selected':''}>游戏 · 免费</option></select>${button('更新榜单','refresh-chart','primary')}</div></div>${x?`${x.warning?`<div class="notice amber">${e(x.warning)}</div>`:''}<p class="muted small">采集于 ${time(x.checkedAt)} · ${x.results.length} 条 · ${link(x.sourceURL,'来源')}</p>${resultsList(x.results,{positions:true})}`:empty('点击更新榜单','首次读取会请求 Apple 的公开榜单接口。','refresh-chart','获取榜单')}</section>`;}
export function reviews(c){const r=c.reviews,a=c.sc.analytics??[],sums=a.reduce((s,r)=>({impressions:s.impressions+r.impressions,pageViews:s.pageViews+r.pageViews,downloads:s.downloads+r.downloads}),{impressions:0,pageViews:0,downloads:0});return `${heading('把搜索曝光与下载决策一起看','公开文字评论与评分分开；曝光和转化来自你导入的报表。')}<div class="stats">${stat('评分数量',c.app.ratingCount??'未知','当前地区公共应用资料')}${stat('曝光',a.length?sums.impressions.toLocaleString():'待导入',a.length?a.length+' 行报表':'尚无转化报表')}${stat('页面访问',a.length?sums.pageViews.toLocaleString():'待导入','报表列 pageViews')}${stat('下载',a.length?sums.downloads.toLocaleString():'待导入','报表列 downloads')}</div><div class="two-even"><section class="panel"><div class="panel-head"><h2>公开文字评论</h2>${button('读取评论','refresh-reviews')}</div>${r?`${r.warning?`<div class="notice amber">${e(r.warning)}</div>`:''}<p class="muted small">${time(r.checkedAt)} · 当前 Feed ${r.results.length} 条 · ${link(r.sourceURL,'来源')}</p>${r.results.length?r.results.map(x=>`<article class="review"><div class="rating-star">${'★'.repeat(Math.min(5,Math.max(0,x.rating)))}<span class="muted small"> ${e(x.author||'')} · ${e(x.date?.slice(0,10)||'')}</span></div><h3>${e(x.title)}</h3><p>${e(x.body)}</p></article>`).join(''):empty('当前 Feed 没有文字评论','评分数量与文字评论数量并不相等。')}`:empty('尚未读取公开评论','点击读取当前地区最新评论。','refresh-reviews','读取评论')}</section><section class="panel"><div class="panel-head"><h2>本地转化报表</h2>${button('导入报表','import-analytics','primary')}</div><p class="muted small">支持标准化的 date、impressions、pageViews、downloads 列。报表仅保存在本机，按当前 App / 地区隔离。</p><div class="toolbar section-gap">${button('下载 CSV 模板','analytics-template','ghost')}${a.length?button('查看报表明细','analytics-detail','ghost'):''}</div>${a.length?`<div class="metric-row"><span>页面访问 / 曝光</span><strong>${sums.impressions?((sums.pageViews/sums.impressions)*100).toFixed(2)+'%':'分母为 0'}</strong></div><div class="metric-row"><span>下载 / 页面访问</span><strong>${sums.pageViews?((sums.downloads/sums.pageViews)*100).toFixed(2)+'%':'分母为 0'}</strong></div><p class="evidence-note">仅当报表口径、日期和渠道一致时，这两个比值才适合比较；不把它们称为全平台转化率。</p>`:empty('尚无转化数据','先从自己的统计资料整理报表，再导入。')}</section></div>`;}
export function settings(c){return `${heading('管理数据来源与本地资料','先接入可验证的数据，再扩展授权服务。')}<div class="two-even"><section class="panel"><h2>产品特征与已有文案</h2><form id="profile-form" class="settings-form"><label>产品类型<select name="kind"><option value="akari" ${c.sc.profile.kind==='akari'?'selected':''}>Akari / Light Up</option><option value="sudoku" ${c.sc.profile.kind==='sudoku'?'selected':''}>Sudoku</option><option value="word" ${c.sc.profile.kind==='word'?'selected':''}>Word Puzzle</option><option value="custom" ${c.sc.profile.kind==='custom'?'selected':''}>自定义</option></select></label><label>已确认的功能 / 场景词（英文逗号或换行分隔）<textarea name="features" rows="3">${e(c.sc.profile.features.join(','))}</textarea></label><label>候选关键词（每行一个）<textarea name="seeds" rows="5">${e(c.sc.profile.seeds.join('\n'))}</textarea></label><label>从公开商店页面手动导入副标题<input name="subtitle" value="${e(c.app.subtitle??'')}"></label><button class="primary" type="submit">保存产品校准</button></form><p class="evidence-note">Search / Lookup API 不返回副标题。手动导入后会标注来源，更新应用资料时保留。</p></section><div class="stack"><section class="panel"><h2>搜索热度与趋势数据</h2><p class="muted small section-gap">导入自己获得的 Apple Ads CSV。必需 searchTerm / keyword、searchPopularity1to100 / popularity；可带 countryOrRegion 和 month / week。</p><div class="toolbar section-gap">${button('导入热度 CSV','import-popularity','primary')}${button('下载模板','popularity-template')}${button('查看已导入数据','popularity-detail','ghost')}</div><p class="evidence-note">热度是相对指标，不是搜索次数。缺少授权时不会用竞品评分量伪造热度。</p>${link('https://developer.apple.com/documentation/apple-ads-platform-api/insights-endpoints','Apple 官方接口')}</section><section class="panel"><h2>本地备份</h2><p class="muted small section-gap">浏览器清理或更换设备后，草稿不会自动恢复。导出可包含选词、隐藏字段、报表和实验；备份由你自行保管。</p><div class="toolbar section-gap">${button('导出 JSON 备份','backup','primary')}${button('导入备份','restore')}${button('导出语言草稿','export-locales','ghost')}</div><div class="metric-row"><span>当前浏览器存储体积</span><strong>${(JSON.stringify(c.db.state).length/1024).toFixed(0)} KB</strong></div></section><section class="panel"><h2>授权服务状态</h2><dl class="definition"><dt>公开 Apple API</dt><dd class="green">已接入 · 查询与缓存</dd><dt>Apple Ads</dt><dd class="amber">CSV 导入可用 · 直接授权未配置</dd><dt>App Store Connect</dt><dd class="muted">尚未绑定 · 只准备本地草稿</dd><dt>模型生成</dt><dd class="muted">尚未配置 · 当前为规则候选</dd></dl><p class="evidence-note">当前静态网站没有密钥输入框。私钥与模型密钥应放在受保护的服务或 Actions Secrets 中。</p></section></div></div>`;}
export function resultsList(results,{action,label,positions=false}={}){return `<div class="result-list">${results.map((a,i)=>`<div class="result-item">${positions?`<span class="position">${i+1}</span>`:''}${appIcon(a)}<div class="result-body"><h3>${link(a.url,a.name)}</h3><p>${e(a.subtitle||a.developer||'')} · ${e(a.category||'')} ${a.ratingCount!=null?'· '+a.ratingCount+' 条评分':''}</p></div>${action?button(label,action,'small',`data-id="${e(a.id)}"`):''}</div>`).join('')}</div>`;}
export function tableOnly(c){return wordTable(c);}
export function trends(c){
 const values=Object.values(c.db.state.popularityHistory??{}).map(popularityTrend).filter(x=>x&&x.latest.country===c.country&&(!c.trendRelevantOnly||['high','medium'].includes(relevance(x.latest.term,c.sc.profile).level))).sort((a,b)=>(b.delta??-999)-(a.delta??-999));
 return `${heading('从真实报表中找变化','按地区比较已导入的同口径周 / 月热度，再检查它与你的产品是否相关。')}<div class="notice">这里是你的导入数据趋势，不能代表全商店完整趋势榜。没有两个有效同口径周期时，变化显示未知。</div><div class="stats">${stat('当前展示词',values.length,'受地区与相关性筛选影响')}${stat('可比较的词',values.filter(x=>x.delta!=null).length,'已有两个不同周期')}${stat('热度上升',values.filter(x=>x.delta>0).length,'仅限导入的数据','green')}${stat('数据来源','CSV 导入','官方直接授权尚未配置','amber')}</div><section class="panel"><div class="panel-head"><h2>相对热度变化</h2><div class="toolbar"><label class="inline-check small"><input id="trend-relevant" type="checkbox" ${c.trendRelevantOnly?'checked':''}>仅高 / 中相关</label>${button('导入热度报表','import-popularity','primary')}</div></div>${values.length?`<div class="table-scroll"><table><thead><tr><th>关键词</th><th>当前周期</th><th>热度</th><th>比较周期</th><th>变化</th><th>相关性</th><th>研究</th></tr></thead><tbody>${values.map(x=>`<tr><td>${e(x.latest.term)}</td><td>${e(x.latest.period)}</td><td class="number">${x.latest.score}</td><td>${e(x.previous?.period??'缺少同口径周期')}</td><td class="number ${x.delta>0?'green':x.delta<0?'amber':'muted'}">${x.delta==null?'—':x.delta>0?'+'+x.delta:x.delta}</td><td>${badge(relevance(x.latest.term,c.sc.profile).label)}</td><td>${button('加入候选','add-candidate','ghost small',`data-term="${e(x.latest.term)}"`)}</td></tr>`).join('')}</tbody></table></div>`:empty('暂无可展示的趋势数据','导入自己的周 / 月热度报表，或关闭相关性筛选查看其他词。','import-popularity','导入热度 CSV')}</section>`;
}
