import test from 'node:test';
import assert from 'node:assert/strict';
import {analyzeDraft,byteCount,charCount,coverage,stem,inferProfile,relevance,actionFor,makeRecord,addHistory,historyDelta,competition,parseCSV,toCSV,importPopularity,importAnalytics,draftProposal,appId,appendPopularity,popularityTrend,validISODate} from '../engine.js';
import {Workspace} from '../storage.js';

const app={id:'6813927466',name:'Fruitlight Doku',subtitle:'Akari Light Up Logic Puzzles',description:'Akari puzzle: place lanterns on a grid. Daily challenge; works offline.',category:'Games'};
test('search absence stays null and does not become rank zero',()=>{const r=makeRecord('akari','us',app,[{trackId:42,trackName:'Other'}],'2026-10-07T04:00:00Z');assert.equal(r.position,null);assert.equal(r.returned,1);assert.equal(r.status,'ok');assert.equal(competition(r,app),null);assert.notEqual(actionFor('akari',r,inferProfile(app),{title:app.name}).label,'移除');});
test('recognize product intent and reject a different puzzle mechanic',()=>{const p=inferProfile(app);assert.equal(relevance('akari puzzle',p).level,'high');assert.equal(relevance('word puzzle',p).level,'low');assert.equal(relevance('light',p).level,'low');assert.equal(relevance('logic grid',p).level,'high');});
test('keep CJK character count and byte budget distinct',()=>{assert.equal(charCount('点灯谜题'),4);assert.equal(byteCount('点灯谜题'),12);const r=analyzeDraft({title:'果灯数谜',subtitle:'逻辑挑战',keywords:'光'.repeat(40)},'zh-Hans');assert(!r.issues.some(x=>x.level==='error'));assert(r.issues.some(x=>x.level==='info'));});
test('catch cross-field plural duplicates without corrupting news/cross',()=>{assert.equal(stem('puzzles'),'puzzle');assert.equal(stem('cross'),'cross');assert.equal(stem('news'),'news');const r=analyzeDraft({title:'Akari Puzzle',subtitle:'Daily puzzles',keywords:'akari,brain'});assert(r.issues.some(x=>x.message.includes('puzzles')));assert(r.issues.some(x=>x.message.includes('akari')));assert(coverage('akari puzzles',{title:'Akari Puzzle'}).title);});
test('field limits include promotional text and description',()=>{const r=analyzeDraft({title:'x'.repeat(31),subtitle:'s'.repeat(31),keywords:'k'.repeat(101),promotionalText:'p'.repeat(171),description:'d'.repeat(4001)});assert.equal(r.issues.filter(x=>x.level==='error').length,5);});
test('CSV supports quotes, line breaks, BOM and safe spreadsheet export',()=>{const csv='\uFEFFkeyword,country\r\n"light up, puzzle",us\r\n"two\nlines",jp';const rows=parseCSV(csv);assert.equal(rows[1][0],'light up, puzzle');assert.equal(rows[2][0],'two\nlines');assert(toCSV([['=HYPERLINK("x")','+evil','plain',-3]]).includes("'=HYPERLINK"));assert.throws(()=>parseCSV('a,b\n"unterminated'));});
test('popularity never fills missing/zero with fake minimum and keeps country',()=>{const r=importPopularity('searchTerm,countryOrRegion,searchPopularity1to100,month\nakari,us,11,2026-09\nakari,jp,45,2026-09\nlogic,us,,2026-09\npuzzle,us,0,2026-09\nlight,us,101,2026-09');assert.equal(r.values.length,2);assert.equal(r.errors.length,3);assert.equal(r.values[1].country,'jp');assert.equal(r.values[0].score,11);});
test('analytics requires complete metrics and allows real zeros',()=>{const r=importAnalytics('date,impressions,pageViews,downloads\n2026-10-01,100,20,5\n2026-10-02,0,0,0\n2026-10-03,100,,5');assert.equal(r.values.length,2);assert.equal(r.errors.length,1);assert.throws(()=>importAnalytics('date,downloads\n2026-10-01,5'));});
test('daily snapshots update same-day source and preserve source separation',()=>{let h=[];h=addHistory(h,{status:'ok',checkedAt:'2026-10-06T01:00:00Z',source:'apple-search-api-v1',position:61,returned:106});h=addHistory(h,{status:'ok',checkedAt:'2026-10-07T01:00:00Z',source:'apple-search-api-v1',position:46,returned:163});assert.equal(historyDelta(h),15);h=addHistory(h,{status:'ok',checkedAt:'2026-10-07T03:00:00Z',source:'apple-search-api-v1',position:null,returned:200});assert.equal(h.length,2);assert.equal(historyDelta(h),null);assert.equal(addHistory(h,{status:'error'}).length,2);});
test('Akari draft preserves brand and respects English field capacities',()=>{const d=draftProposal(app,inferProfile(app),{title:app.name,subtitle:app.subtitle,keywords:''});assert.equal(d.title,'Fruitlight Doku: Akari Puzzles');assert.equal(charCount(d.title),30);assert.equal(charCount(d.subtitle),29);assert.equal(analyzeDraft(d).issues.filter(x=>x.level==='error').length,0);assert.doesNotThrow(()=>draftProposal(app,inferProfile(app),{},'unknown'));});
test('App IDs only resolve from plain IDs or actual Apple URLs',()=>{assert.equal(appId('https://apps.apple.com/us/app/test/id6813927466'),'6813927466');assert.equal(appId('6813927466'),'6813927466');assert.equal(appId('https://example.com/id6813927466'),null);});
test('report trends compare only distinct periods of the same granularity',()=>{let h=[];h=appendPopularity(h,{term:'akari',country:'us',score:11,period:'2026-08',granularity:'month'});h=appendPopularity(h,{term:'akari',country:'us',score:14,period:'2026-09',granularity:'month'});assert.equal(popularityTrend(h).delta,3);h=appendPopularity(h,{term:'akari',country:'us',score:16,period:'2026-09-27',granularity:'week'});assert.equal(popularityTrend(h).delta,null);assert.equal(popularityTrend(h).latest.score,16);assert.equal(popularityTrend([{score:5,period:'未提供',granularity:'unknown'}]).delta,null);});
test('invalid calendar dates do not enter analytics',()=>{assert.equal(validISODate('2026-02-29'),false);assert.equal(validISODate('2024-02-29'),true);assert.equal(importAnalytics('date,impressions,pageViews,downloads\n2026-04-31,1,1,1').values.length,0);});
test('competition proxy excludes the app itself',()=>{const r={term:'akari',topResults:[app,...Array.from({length:4},(_,i)=>({id:String(i),name:'Akari '+i,category:'Games',ratingCount:0}))]};assert.equal(competition(r,app),null);});
test('history uses UTC days and an older remote point cannot replace a newer local point',()=>{let h=addHistory([],{status:'ok',checkedAt:'2026-10-08T00:30:00+08:00',source:'apple-search-api-v1',position:62,returned:100});assert.equal(h[0].date,'2026-10-07');h=addHistory(h,{status:'ok',checkedAt:'2026-10-07T15:00:00Z',source:'apple-search-api-v1',position:61,returned:100});assert.equal(h[0].position,62);});
test('country workspaces and drafts remain separate; invalid restore is atomic',()=>{
 const memory=new Map();globalThis.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};
 const seed={apps:[app],searches:[]};const w=new Workspace(seed);w.addWord('akari');w.current.words.akari.tracked=true;w.current.drafts['en-US']={title:'Test',subtitle:'S',keywords:'brain'};w.save();w.select(app.id,'jp');assert.equal(Object.keys(w.current.words).length,0);assert.equal(w.current.metadata.subtitle,'');assert(w.current.metadata.countryUnverified);w.select(app.id,'us');assert(w.current.words.akari.tracked);assert.equal(w.current.drafts['en-US'].title,'Test');const old=w.export();const bad=JSON.parse(old);delete bad.scopes[app.id+':us'].profile;assert.throws(()=>w.restore(JSON.stringify(bad)));assert.equal(w.current.drafts['en-US'].title,'Test');w.restore(old);assert(w.current.words.akari.tracked);assert.throws(()=>w.addWord('__proto__'));});
test('backup restore rejects invalid nested metrics before replacing current work',()=>{
 const memory=new Map();globalThis.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};
 const w=new Workspace({apps:[app],searches:[]});w.current.drafts['en-US']={title:'Keep me',subtitle:'S',keywords:'brain'};
 const original=w.export(),bad=JSON.parse(original),scope=bad.scopes[app.id+':us'];
 scope.analytics=[{date:'2026-10-07',impressions:'<img src=x>',pageViews:1,downloads:1}];assert.throws(()=>w.restore(JSON.stringify(bad)));assert.equal(w.current.drafts['en-US'].title,'Keep me');
 scope.analytics=[];scope.competitors=[{id:'42',name:'Other',ratingCount:'<b>fake</b>'}];assert.throws(()=>w.restore(JSON.stringify(bad)));
 scope.competitors=[];scope.words.akari={term:'akari',record:{status:'ok',returned:100,position:'<b>1</b>',topResults:[]}};assert.throws(()=>w.restore(JSON.stringify(bad)));
 scope.words={};bad.popularity={'us|akari':{term:'akari',country:'us',score:Infinity}};assert.throws(()=>w.restore(JSON.stringify(bad)));
 w.restore(original);assert.equal(w.current.drafts['en-US'].title,'Keep me');
});
